version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CulTechConnect
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network
    restart: unless-stopped

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
