spring:
  application:
    name: reservation
  config:
    import: optional:configserver:http://localhost:8888
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
    events-service-url: http://localhost:8083
