eureka:
  client:
    register-with-eureka: true
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: events
          uri: http://localhost:8083
          predicates:
            - Path=/events/**
        - id: reservation
          uri: http://localhost:8091
          predicates:
            - Path=/reservation/**
            -
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

management:
  tracing:
    sampling:
      probability: 1.0
